"""create initial tables

Revision ID: 35989c7d5d9e
Revises: 
Create Date: 2026-01-21 17:15:23.170862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35989c7d5d9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('webhook_url', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_job_batches',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invariants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'owner_id', name='prompt_name_version_owner')
    )
    op.create_index(op.f('ix_prompts_owner_id'), 'prompts', ['owner_id'], unique=False)
    op.create_table('tickets',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('triage_status', sa.Enum('PENDING', 'ON_TRIAGE', 'COMPLETED', 'FAILED', name='triage_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_external_id'), 'tickets', ['external_id'], unique=True)
    op.create_index(op.f('ix_tickets_owner_id'), 'tickets', ['owner_id'], unique=False)
    op.create_table('triage_jobs',
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='triage_job_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_jobs_ticket_id'), 'triage_jobs', ['ticket_id'], unique=False)
    op.create_table('triage_job_batch_items',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('triage_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='triage_job_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['triage_job_batches.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_job_id'], ['triage_jobs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_job_batch_items_batch_id'), 'triage_job_batch_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_triage_job_batch_items_triage_job_id'), 'triage_job_batch_items', ['triage_job_id'], unique=False)
    op.create_table('triage_job_logs',
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('triage_job_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_job_id'], ['triage_jobs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_job_logs_prompt_id'), 'triage_job_logs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_triage_job_logs_triage_job_id'), 'triage_job_logs', ['triage_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_job_logs_triage_job_id'), table_name='triage_job_logs')
    op.drop_index(op.f('ix_triage_job_logs_prompt_id'), table_name='triage_job_logs')
    op.drop_table('triage_job_logs')
    op.drop_index(op.f('ix_triage_job_batch_items_triage_job_id'), table_name='triage_job_batch_items')
    op.drop_index(op.f('ix_triage_job_batch_items_batch_id'), table_name='triage_job_batch_items')
    op.drop_table('triage_job_batch_items')
    op.drop_index(op.f('ix_triage_jobs_ticket_id'), table_name='triage_jobs')
    op.drop_table('triage_jobs')
    op.drop_index(op.f('ix_tickets_owner_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_prompts_owner_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_table('triage_job_batches')
    op.drop_table('owners')
    # ### end Alembic commands ###
